export const QUOTES = [
    // --- SCIENTISTS ---
    { text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", author: "Marie Curie" },
    { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
    { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
    { text: "The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.", author: "Albert Einstein" },
    { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
    { text: "The important thing is not to stop questioning. Curiosity has its own reason for existence.", author: "Albert Einstein" },
    { text: "Research is seeing what everybody else has seen and thinking what nobody else has thought.", author: "Albert Szent-Györgyi" },
    { text: "All truths are easy to understand once they are discovered; the point is to discover them.", author: "Galileo Galilei" },
    { text: "Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world.", author: "Louis Pasteur" },
    { text: "Life need not be easy, provided only that it is not empty.", author: "Lise Meitner" },
    { text: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton" },
    { text: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson" },
    { text: "Equipped with his five senses, man explores the universe around him and calls the adventure Science.", author: "Edwin Hubble" },
    { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" }, // Philosopher/Scientist overlap
    { text: "The science of today is the technology of tomorrow.", author: "Edward Teller" },
    { text: "We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.", author: "Stephen Hawking" },
    { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
    { text: "I seem to have been only like a boy playing on the seashore, and diverting myself in now and then finding a smoother pebble or a prettier shell than ordinary, whilst the great ocean of truth lay all undiscovered before me.", author: "Isaac Newton" },
    { text: "Everything is theoretically impossible, until it is done.", author: "Robert A. Heinlein" }, // Sci-fi, but relevant
    { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
    { text: "It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is most adaptable to change.", author: "Charles Darwin" },
    { text: "Science cannot solve the ultimate mystery of nature. And that is because, in the last analysis, we ourselves are a part of the mystery that we are trying to solve.", author: "Max Planck" },
    { text: "An experiment is a question which science poses to Nature, and a measurement is the recording of Nature's answer.", author: "Max Planck" },
    { text: "Falsity in intellectual action is intellectual immorality.", author: "Thomas Chrowder Chamberlin" },
    { text: "The black holes of nature are the most perfect macroscopic objects there are in the universe: the only elements in their construction are our concepts of space and time.", author: "Subrahmanyan Chandrasekhar" },
    { text: "Every great advance in science has issued from a new audacity of imagination.", author: "John Dewey" },
    { text: "Nature uses as little as possible of anything.", author: "Johannes Kepler" },
    { text: "Where there is matter, there is geometry.", author: "Johannes Kepler" },
    { text: "One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don't throw it away.", author: "Stephen Hawking" },
    { text: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking" },
    { text: "Science is the acceptance of what works and the rejection of what does not. That needs more courage than we might think.", author: "Jacob Bronowski" },
    { text: "There is no law except the law that there is no law.", author: "John Archibald Wheeler" },
    { text: "If you want to have good ideas you must have many ideas.", author: "Linus Pauling" },
    { text: "Satisfaction of one's curiosity is one of the greatest sources of happiness in life.", author: "Linus Pauling" },
    { text: "I wasn't always successful, but I've always had a lot of fun.", author: "Thomas Edison" }, // Inventor/Applied Sci
    { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
    { text: "Whatever nature has in store for mankind, unpleasant as it may be, men must accept, for ignorance is never better than knowledge.", author: "Enrico Fermi" },
    { text: "There are two possible outcomes: if the result confirms the hypothesis, then you've made a measurement. If the result is contrary to the hypothesis, then you've made a discovery.", author: "Enrico Fermi" },
    { text: "Nothing gives one a more spur to rise to one's best than a friend's call for help.", author: "Niels Bohr" },
    { text: "An expert is a person who has made all the mistakes that can be made in a very narrow field.", author: "Niels Bohr" },
    { text: "Prediction is very difficult, especially if it's about the future.", author: "Niels Bohr" },
    { text: "Identify the problem, remove the problem.", author: "Fritz Zwicky" },
    { text: "The farther the experiment is from theory, the closer it is to the Nobel Prize.", author: "Irene Joliot-Curie" },
    { text: "You cannot hope to build a better world without improving the individuals. To that end each of us must work for his own improvement.", author: "Marie Curie" },
    { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie" },
    { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" }, // Opera singer, but often attributed generally. Let's stick to scientists.
    { text: "Above all, don't fear difficult moments. The best comes from them.", author: "Rita Levi-Montalcini" },
    { text: "I tell young people: Do not think of yourself, think of others. Think of the future that awaits you, think about what you can do and do not fear anything.", author: "Rita Levi-Montalcini" },
    { text: "Science and everyday life cannot and should not be separated.", author: "Rosalind Franklin" },
    { text: "In my view, all that is necessary for faith is the belief that by doing our best we shall succeed in our aims: the improvement of mankind.", author: "Rosalind Franklin" },
    { text: "I didn't want to just know names of things. I remember really wanting to know how it all worked.", author: "Elizabeth Blackburn" },
    { text: "We shouldn't be afraid of the unknown, because the unknown is just the beginning of a new adventure.", author: "Elizabeth Blackburn" },
    { text: "Don't confirm the theory. Test it.", author: "Barbara McClintock" },
    { text: "I was just so interested in what I was doing I could hardly wait to get up in the morning and get at it.", author: "Barbara McClintock" },
    { text: "If you know you are on the right track, if you have this inner knowledge, then nobody can turn you off... no matter what they say.", author: "Barbara McClintock" },
    { text: "DNA is like a computer program but far, far more advanced than any software ever created.", author: "Bill Gates" }, // Tech, adjacent
    { text: "Biology is the most powerful technology in the world. DNA is software, protein are hardware, cells are factories.", author: "Arvind Gupta" },
    { text: "Evolution has been a magnificent improviser, not a grand architect.", author: "Richard Dawkins" },
    { text: "We are survival machines – robot vehicles blindly programmed to preserve the selfish molecules known as genes.", author: "Richard Dawkins" },
    { text: "The more you study, the more you know; how less you know.", author: "Imhotep" },
    { text: "Chance favors the prepared mind.", author: "Louis Pasteur" },
    { text: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it.", author: "Charles F. Kettering" },
    { text: "The outcome of any serious research can only be to make two questions grow where only one grew before.", author: "Thorstein Veblen" },
    { text: "Hypothesis: a supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation.", author: "Dictionary of Science" }, // Filler
    { text: "The most exciting phrase to hear in science, the one that heralds new discoveries, is not 'Eureka!' but 'That's funny...'", author: "Isaac Asimov" },
    { text: "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.", author: "Isaac Asimov" },
    { text: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", author: "Isaac Asimov" },
    { text: "Anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that 'my ignorance is just as good as your knowledge.'", author: "Isaac Asimov" },
    { text: "It is the tension between creativity and skepticism that has produced the stunning and unexpected findings of science.", author: "Carl Sagan" },
    { text: "We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.", author: "Carl Sagan" },
    { text: "Absence of evidence is not evidence of absence.", author: "Carl Sagan" },
    { text: "Who is more humble? The scientist who looks at the universe with an open mind and accepts whatever the universe has to teach us, or somebody who says everything in this book must be considered the literal truth and never mind the fallibility of all the human beings involved?", author: "Carl Sagan" },
    { text: "For me, it is far better to grasp the Universe as it really is than to persist in delusion, however satisfying and reassuring.", author: "Carl Sagan" },
    { text: "Extinction is the rule. Survival is the exception.", author: "Carl Sagan" },
    { text: "Every one of us is, in the cosmic perspective, precious. If a human disagrees with you, let him live. In a hundred billion galaxies, you will not find another.", author: "Carl Sagan" },
    { text: "We make our world significant by the courage of our questions and the depth of our answers.", author: "Carl Sagan" },
    { text: "Cosmology brings us face to face with the deepest mysteries, questions that were once treated only in religion and myth.", author: "Carl Sagan" },
    { text: "Biology is the study of complex things that appear to have been designed for a purpose.", author: "Richard Dawkins" },
    { text: "Science is the poetry of reality.", author: "Richard Dawkins" },
    { text: "We die, and that makes us the lucky ones. Most people are never going to die because they are never going to be born.", author: "Richard Dawkins" },
    { text: "There is a grandeur in this view of life.", author: "Charles Darwin" },
    { text: "A mathematician is a machine for turning coffee into theorems.", author: "Alfréd Rényi" }, // Often attr to Erdos
    { text: "Black holes are where God divided by zero.", author: "Steven Wright" }, // Humor/Sci
    { text: "Time is a drug. Too much of it kills you.", author: "Terry Pratchett" }, // Lit/Phil
    { text: "Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it.", author: "Terry Pratchett" },

    // --- PHILOSOPHERS ---
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "To find yourself, think for yourself.", author: "Socrates" },
    { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
    { text: "He who is not contented with what he has, would not be contented with what he would like to have.", author: "Socrates" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "The whole is more than the sum of its parts.", author: "Aristotle" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
    { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { text: "When we see men of a contrary character, we should turn inwards and examine ourselves.", author: "Confucius" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Our greatest glory is not in never failing, but in rising up every time we fail.", author: "Ralph Waldo Emerson" },
    { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
    { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard" },
    { text: "Life can only be understood backwards; but it must be lived forwards.", author: "Søren Kierkegaard" },
    { text: "I think, therefore I am.", author: "René Descartes" },
    { text: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes" },
    { text: "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.", author: "René Descartes" },
    { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich Nietzsche" },
    { text: "Man is the measure of all things.", author: "Protagoras" },
    { text: "Everything changes and nothing stands still.", author: "Heraclitus" },
    { text: "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", author: "Heraclitus" },
    { text: "The only constant in life is change.", author: "Heraclitus" },
    { text: "We live in the best of all possible worlds.", author: "Gottfried Wilhelm Leibniz" },
    { text: "Liberty consists in doing what one desires.", author: "John Stuart Mill" },
    { text: "One person with a belief is equal to ninety-nine who have only interests.", author: "John Stuart Mill" },
    { text: "Man is born free, and everywhere he is in chains.", author: "Jean-Jacques Rousseau" },
    { text: "The world of reality has its limits; the world of imagination is boundless.", author: "Jean-Jacques Rousseau" },
    { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
    { text: "I disapprove of what you say, but I will defend to the death your right to say it.", author: "Voltaire" }, // Often attr to Evelyn Beatrice Hall
    { text: "Judge a man by his questions rather than by his answers.", author: "Voltaire" },
    { text: "Common sense is not so common.", author: "Voltaire" },
    { text: "Perfection is attained by slow degrees; it requires the hand of time.", author: "Voltaire" },
    { text: "Knowledge is power.", author: "Francis Bacon" },
    { text: "A wise man will make more opportunities than he finds.", author: "Francis Bacon" },
    { text: "Wonder is the seed of knowledge.", author: "Francis Bacon" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci" },
    { text: "Poor is the pupil who does not surpass his master.", author: "Leonardo da Vinci" },
    { text: "The greatest deception men suffer is from their own opinions.", author: "Leonardo da Vinci" },
    { text: "Entities should not be multiplied unnecessarily.", author: "William of Ockham" },
    { text: "There is nothing permanent except change.", author: "Heraclitus" },
    { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin" }, // Lit/Phil
    { text: "Freedom is the open window through which pours the sunlight of the human spirit and human dignity.", author: "Herbert Hoover" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bil Keane" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
    { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
    { text: "It is better to light a candle than curse the darkness.", author: "Eleanor Roosevelt" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King, Jr." },
    { text: "The time is always right to do what is right.", author: "Martin Luther King, Jr." },
    { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King, Jr." },
    { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King, Jr." },
    { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King, Jr." },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Kites rise highest against the wind, not with it.", author: "Winston Churchill" },
    { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
    { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
    { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
    { text: "I walk slowly, but I never walk backward.", author: "Abraham Lincoln" },
    { text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
    { text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", author: "John F. Kennedy" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
    { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
    { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
    { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { text: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
    { text: "Reality is merely an illusion, albeit a very persistent one.", author: "Albert Einstein" },
    { text: "Coincidence is God's way of remaining anonymous.", author: "Albert Einstein" },
    { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
    { text: "Intellectual growth should commence at birth and cease only at death.", author: "Albert Einstein" },
    { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
    { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein" },
    { text: "The hardest thing to understand in the world is the income tax.", author: "Albert Einstein" }, // Humor
    { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
    { text: "Great spirits have always encountered violent opposition from mediocre minds.", author: "Albert Einstein" },
    { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
    { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { text: "Science without religion is lame, religion without science is blind.", author: "Albert Einstein" },
    { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
    { text: "If you can't explain it to a six year old, you don't understand it yourself.", author: "Albert Einstein" }, // Apocryphal
    { text: "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.", author: "Albert Einstein" },
    { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { text: "Time is an illusion.", author: "Albert Einstein" },
    { text: "God does not play dice with the universe.", author: "Albert Einstein" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The definition of insanity is doing the same thing over and over again and expecting different results.", author: "Albert Einstein" }, // Apocryphal
    { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
    { text: "A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy?", author: "Albert Einstein" },
    { text: "The years of anxious searching in the dark, with their intense longing, their alternations of confidence and exhaustion, and final emergence into the light—only those who have experienced it can understand that.", author: "Albert Einstein" }, // Relevant to research
    { text: "The mind is everything. What you think you become.", author: "Buddha" }, // Philosophy/Religion
    { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
    { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde" },
    { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
    { text: "Experience is the name everyone gives to their mistakes.", author: "Oscar Wilde" },
    { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
    { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde" },
    { text: "I can resist everything except temptation.", author: "Oscar Wilde" }, // Humor
    { text: "Art is the lie that enables us to realize the truth.", author: "Pablo Picasso" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
    { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
    { text: "Inspiration exists, but it must find you working.", author: "Pablo Picasso" },
    { text: "It takes a long time to become young.", author: "Pablo Picasso" },
    { text: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso" }
];
